CREATE TABLE IF NOT EXISTS transaksi_stok (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barang_id INTEGER NOT NULL REFERENCES barang(id) ON DELETE RESTRICT,
    jenis VARCHAR(10) NOT NULL CHECK (jenis IN ('masuk', 'keluar')),
    jumlah INTEGER NOT NULL CHECK (jumlah > 0),
    catatan TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_transaksi_stok_barang_tanggal
    ON transaksi_stok (barang_id, created_at DESC);